version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: wasim
    network_mode: "host"
    volumes:
      - /D/JellyfinDocker/config:/config
      - /D/JellyfinDocker/cache:/cache
      - /D/Movie:/media
      
    restart: "unless-stopped"
    # Optional - alternative address used for autodiscovery
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://example.com